### ISSUE TITLE
BMPString uses invalid UTF16 encoding

### ISSUE THREAD

**Issue by johndoe31415** [google/x509test#5]
Hi David,

hope you are well. I have been coding some more and checking against your great x509test toolkit. I believe I've found an issue in xf-ext-cert-policies-bmp-unotice. In particular, you define the explicitText BMPString as:

```
  BMPString { "User notice" }  # explicitText
```

Clearly, this violates the RFC because the type is a BMPString. However, a BMPString is UTF-16, but "User notice" is 11 characters wide. I.e., a proper BMPString parser doesn't even validate the encoded string, but chokes already on the encoding of the string itself. The testcase does pose an invalid certificate, but it does not test not what it should actually test.

It can be easily fixed by either of:

1. Change "User notice" to "User noticex" (or any other valid UTF-16 string)
2. Change BMPString to VisibleString

Thanks & HTH,
All the best,
Joe

**Comment by daviddrysdale** [comment]
Good spot!  

X.690-0207 has:

> 8.21.8 For the BMPString type, the octet string shall contain the octets specified in ISO/IEC 10646-1, using the 2-octet BMP form (see 13.1 of ISO/IEC 10646-1). 

so it looks like this text should be in UCS-2.

**Comment by johndoe31415** [comment]
Looks great to me, thanks a bunch!
